<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:tns="UnityEditor.UIElements" elementFormDefault="qualified" targetNamespace="UnityEditor.UIElements" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="UnityEngine.UIElements.xsd" namespace="UnityEngine.UIElements" />
  <xs:import schemaLocation="UnityEngine.xsd" namespace="UnityEngine" />
  <xs:complexType name="ProjectSettingsThemeDropdownType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q1="UnityEngine.UIElements" base="q1:DropdownFieldType">
        <xs:choice />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="ProjectSettingsThemeDropdown" xmlns:q2="UnityEngine.UIElements" substitutionGroup="q2:DropdownField" type="tns:ProjectSettingsThemeDropdownType" />
  <xs:complexType name="UIPrefColorSectionType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q3="UnityEngine.UIElements" base="q3:VisualElementType">
        <xs:choice />
        <xs:attribute name="color-prefix" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="UIPrefColorSection" xmlns:q4="UnityEngine.UIElements" substitutionGroup="q4:VisualElement" type="tns:UIPrefColorSectionType" />
  <xs:complexType name="SyntaxHighlightConfigurationType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q5="UnityEngine.UIElements" base="q5:VisualElementType">
        <xs:choice />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="SyntaxHighlightConfiguration" xmlns:q6="UnityEngine.UIElements" substitutionGroup="q6:VisualElement" type="tns:SyntaxHighlightConfigurationType" />
  <xs:complexType name="ToolbarSearchFieldType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q7="UnityEngine.UIElements" base="q7:VisualElementType">
        <xs:choice />
        <xs:attribute name="placeholder-text" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="ToolbarSearchField" xmlns:q8="UnityEngine.UIElements" substitutionGroup="q8:VisualElement" type="tns:ToolbarSearchFieldType" />
  <xs:complexType name="ToolbarButtonType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q9="UnityEngine.UIElements" base="q9:ButtonType">
        <xs:choice />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="ToolbarButton" xmlns:q10="UnityEngine.UIElements" substitutionGroup="q10:Button" type="tns:ToolbarButtonType" />
  <xs:complexType name="RenderingLayerMaskFieldType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q11="UnityEngine.UIElements" base="q11:BindableElementType">
        <xs:choice />
        <xs:attribute name="label" type="xs:string" />
        <xs:attribute default="1" name="value" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="RenderingLayerMaskField" xmlns:q12="UnityEngine.UIElements" substitutionGroup="q12:BindableElement" type="tns:RenderingLayerMaskFieldType" />
  <xs:complexType name="CategoryDropdownFieldType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q13="UnityEngine.UIElements" base="q13:BindableElementType">
        <xs:choice />
        <xs:attribute name="label" type="xs:string" />
        <xs:attribute name="value" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="CategoryDropdownField" xmlns:q14="UnityEngine.UIElements" substitutionGroup="q14:BindableElement" type="tns:CategoryDropdownFieldType" />
  <xs:complexType name="BackgroundFieldType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q15="UnityEngine.UIElements" base="q15:BindableElementType">
        <xs:choice />
        <xs:attribute name="label" type="xs:string" />
        <xs:attribute default="none" name="value" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="BackgroundField" xmlns:q16="UnityEngine.UIElements" substitutionGroup="q16:BindableElement" type="tns:BackgroundFieldType" />
  <xs:complexType name="FontFieldType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q17="UnityEngine.UIElements" base="q17:BindableElementType">
        <xs:choice />
        <xs:attribute name="label" type="xs:string" />
        <xs:attribute name="value" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="FontField" xmlns:q18="UnityEngine.UIElements" substitutionGroup="q18:BindableElement" type="tns:FontFieldType" />
  <xs:complexType name="ToolbarSpacerType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q19="UnityEngine.UIElements" base="q19:VisualElementType">
        <xs:choice />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="ToolbarSpacer" xmlns:q20="UnityEngine.UIElements" substitutionGroup="q20:VisualElement" type="tns:ToolbarSpacerType" />
  <xs:complexType name="ToolbarMenuType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q21="UnityEngine.UIElements" base="q21:TextElementType">
        <xs:choice />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="ToolbarMenu" xmlns:q22="UnityEngine.UIElements" substitutionGroup="q22:TextElement" type="tns:ToolbarMenuType" />
  <xs:complexType name="GradientFieldType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q23="UnityEngine.UIElements" base="q23:BindableElementType">
        <xs:choice />
        <xs:attribute name="label" type="xs:string" />
        <xs:attribute default="Blend:{0,#FFFFFFFF};{1,#FFFFFFFF}+{0,1};{1,1}" name="value" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="GradientField" xmlns:q24="UnityEngine.UIElements" substitutionGroup="q24:BindableElement" type="tns:GradientFieldType" />
  <xs:complexType name="EnumFlagsFieldType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q25="UnityEngine.UIElements" base="q25:BindableElementType">
        <xs:choice />
        <xs:attribute name="label" type="xs:string" />
        <xs:attribute name="value" type="xs:string" />
        <xs:attribute name="type" type="xs:string" />
        <xs:attribute default="false" name="include-obsolete-values" type="xs:boolean" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="EnumFlagsField" xmlns:q26="UnityEngine.UIElements" substitutionGroup="q26:BindableElement" type="tns:EnumFlagsFieldType" />
  <xs:complexType name="ColorFieldType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q27="UnityEngine.UIElements" base="q27:BindableElementType">
        <xs:choice />
        <xs:attribute name="label" type="xs:string" />
        <xs:attribute default="rgba(0, 0, 0, 0)" name="value" type="xs:string" />
        <xs:attribute default="false" name="show-eye-dropper" type="xs:boolean" />
        <xs:attribute default="true" name="show-alpha" type="xs:boolean" />
        <xs:attribute default="false" name="hdr" type="xs:boolean" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="ColorField" xmlns:q28="UnityEngine.UIElements" substitutionGroup="q28:BindableElement" type="tns:ColorFieldType" />
  <xs:complexType name="TagFieldType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q29="UnityEngine.UIElements" base="q29:BindableElementType">
        <xs:choice />
        <xs:attribute name="label" type="xs:string" />
        <xs:attribute name="value" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="TagField" xmlns:q30="UnityEngine.UIElements" substitutionGroup="q30:BindableElement" type="tns:TagFieldType" />
  <xs:complexType name="UIAnimationClipFieldType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q31="UnityEngine.UIElements" base="q31:BindableElementType">
        <xs:choice />
        <xs:attribute name="label" type="xs:string" />
        <xs:attribute name="value" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="UIAnimationClipField" xmlns:q32="UnityEngine.UIElements" substitutionGroup="q32:BindableElement" type="tns:UIAnimationClipFieldType" />
  <xs:complexType name="ToolbarToggleType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q33="UnityEngine.UIElements" base="q33:ToggleType">
        <xs:choice />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="ToolbarToggle" xmlns:q34="UnityEngine.UIElements" substitutionGroup="q34:Toggle" type="tns:ToolbarToggleType" />
  <xs:complexType name="ToolbarType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q35="UnityEngine.UIElements" base="q35:VisualElementType">
        <xs:choice />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="Toolbar" xmlns:q36="UnityEngine.UIElements" substitutionGroup="q36:VisualElement" type="tns:ToolbarType" />
  <xs:complexType name="ObjectFieldType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q37="UnityEngine.UIElements" base="q37:BindableElementType">
        <xs:choice />
        <xs:attribute name="label" type="xs:string" />
        <xs:attribute name="value" type="xs:string" />
        <xs:attribute default="true" name="allow-scene-objects" type="xs:boolean" />
        <xs:attribute default="true" name="allow-builtin-resources" type="xs:boolean" />
        <xs:attribute default="UnityEngine.Object, UnityEngine.CoreModule" name="type" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="ObjectField" xmlns:q38="UnityEngine.UIElements" substitutionGroup="q38:BindableElement" type="tns:ObjectFieldType" />
  <xs:complexType name="ToolbarBreadcrumbsType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q39="UnityEngine.UIElements" base="q39:VisualElementType">
        <xs:choice />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="ToolbarBreadcrumbs" xmlns:q40="UnityEngine.UIElements" substitutionGroup="q40:VisualElement" type="tns:ToolbarBreadcrumbsType" />
  <xs:complexType name="UnityEventItemType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q41="UnityEngine.UIElements" base="q41:VisualElementType">
        <xs:choice />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="UnityEventItem" xmlns:q42="UnityEngine.UIElements" substitutionGroup="q42:VisualElement" type="tns:UnityEventItemType" />
  <xs:complexType name="CurveFieldType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q43="UnityEngine.UIElements" base="q43:BindableElementType">
        <xs:choice />
        <xs:attribute name="label" type="xs:string" />
        <xs:attribute default="+(ClampForever,ClampForever)" name="value" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="CurveField" xmlns:q44="UnityEngine.UIElements" substitutionGroup="q44:BindableElement" type="tns:CurveFieldType" />
  <xs:complexType name="LayerFieldType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q45="UnityEngine.UIElements" base="q45:BindableElementType">
        <xs:choice />
        <xs:attribute name="label" type="xs:string" />
        <xs:attribute default="0" name="value" type="xs:int" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="LayerField" xmlns:q46="UnityEngine.UIElements" substitutionGroup="q46:BindableElement" type="tns:LayerFieldType" />
  <xs:complexType name="LayerMaskFieldType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q47="UnityEngine.UIElements" base="q47:MaskFieldType">
        <xs:choice />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="LayerMaskField" xmlns:q48="UnityEngine.UIElements" substitutionGroup="q48:MaskField" type="tns:LayerMaskFieldType" />
  <xs:complexType name="RatioFieldType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q49="UnityEngine.UIElements" base="q49:BindableElementType">
        <xs:choice />
        <xs:attribute name="label" type="xs:string" />
        <xs:attribute name="value" type="xs:string" />
        <xs:attribute default="1000" name="max-length" type="xs:int" />
        <xs:attribute default="false" name="password" type="xs:boolean" />
        <xs:attribute name="mask-character" type="xs:string" />
        <xs:attribute name="placeholder-text" type="xs:string" />
        <xs:attribute default="false" name="hide-placeholder-on-focus" type="xs:boolean" />
        <xs:attribute default="false" name="readonly" type="xs:boolean" />
        <xs:attribute default="false" name="is-delayed" type="xs:boolean" />
        <xs:attribute default="Hidden" name="vertical-scroller-visibility" type="q49:ScrollerVisibilityType" />
        <xs:attribute default="true" name="select-all-on-mouse-up" type="xs:boolean" />
        <xs:attribute default="true" name="select-all-on-focus" type="xs:boolean" />
        <xs:attribute default="true" name="select-word-by-double-click" type="xs:boolean" />
        <xs:attribute default="true" name="select-line-by-triple-click" type="xs:boolean" />
        <xs:attribute default="true" name="emoji-fallback-support" type="xs:boolean" />
        <xs:attribute default="false" name="hide-soft-keyboard" type="xs:boolean" />
        <xs:attribute default="false" name="hide-mobile-input" type="xs:boolean" />
        <xs:attribute default="Default" name="keyboard-type" xmlns:q50="UnityEngine" type="q50:TouchScreenKeyboardTypeType" />
        <xs:attribute default="false" name="auto-correction" type="xs:boolean" />
        <xs:attribute default="true" name="support-expressions" type="xs:boolean" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="RatioField" xmlns:q51="UnityEngine.UIElements" substitutionGroup="q51:BindableElement" type="tns:RatioFieldType" />
  <xs:complexType name="FontDefinitionFieldType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q52="UnityEngine.UIElements" base="q52:BindableElementType">
        <xs:choice />
        <xs:attribute name="label" type="xs:string" />
        <xs:attribute name="value" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="FontDefinitionField" xmlns:q53="UnityEngine.UIElements" substitutionGroup="q53:BindableElement" type="tns:FontDefinitionFieldType" />
  <xs:complexType name="PropertyFieldType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q54="UnityEngine.UIElements" base="q54:VisualElementType">
        <xs:choice />
        <xs:attribute name="binding-path" type="xs:string" />
        <xs:attribute name="label" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="PropertyField" xmlns:q55="UnityEngine.UIElements" substitutionGroup="q55:VisualElement" type="tns:PropertyFieldType" />
  <xs:complexType name="ToolbarPopupSearchFieldType">
    <xs:complexContent mixed="false">
      <xs:extension base="tns:ToolbarSearchFieldType">
        <xs:choice />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="ToolbarPopupSearchField" substitutionGroup="tns:ToolbarSearchField" type="tns:ToolbarPopupSearchFieldType" />
  <xs:complexType name="DropdownOptionListItemType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q56="UnityEngine.UIElements" base="q56:BindableElementType">
        <xs:choice />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="DropdownOptionListItem" xmlns:q57="UnityEngine.UIElements" substitutionGroup="q57:BindableElement" type="tns:DropdownOptionListItemType" />
  <xs:complexType name="CursorFieldType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q58="UnityEngine.UIElements" base="q58:BindableElementType">
        <xs:choice />
        <xs:attribute name="label" type="xs:string" />
        <xs:attribute default=" 0 0" name="value" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="CursorField" xmlns:q59="UnityEngine.UIElements" substitutionGroup="q59:BindableElement" type="tns:CursorFieldType" />
  <xs:complexType name="InspectorElementType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q60="UnityEngine.UIElements" base="q60:BindableElementType">
        <xs:choice />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="InspectorElement" xmlns:q61="UnityEngine.UIElements" substitutionGroup="q61:BindableElement" type="tns:InspectorElementType" />
  <xs:complexType name="ObjectFieldWithPromptType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q62="UnityEngine.UIElements" base="q62:BindableElementType">
        <xs:choice />
        <xs:attribute name="label" type="xs:string" />
        <xs:attribute name="value" type="xs:string" />
        <xs:attribute default="false" name="allow-scene-objects" type="xs:boolean" />
        <xs:attribute name="type" type="xs:string" />
        <xs:attribute name="title" type="xs:string" />
        <xs:attribute name="message" type="xs:string" />
        <xs:attribute name="removal-message" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="ObjectFieldWithPrompt" xmlns:q63="UnityEngine.UIElements" substitutionGroup="q63:BindableElement" type="tns:ObjectFieldWithPromptType" />
</xs:schema>